import { build } from "esbuild";
import {
	existsSync,
	readFileSync,
	readdirSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const piRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entryPoint = join(piRoot, "extension", "mcp-client.ts");
const bundlePath = join(piRoot, "extension", "mcp-client.bundle.cjs");
const noticesPath = join(piRoot, "extension", "THIRD_PARTY_NOTICES.txt");
const check = process.argv.includes("--check");

function packageNameFromInput(input) {
	const marker = `node_modules${sep}`;
	const normalized = resolve(input);
	const index = normalized.lastIndexOf(marker);
	if (index < 0) return undefined;
	const parts = normalized.slice(index + marker.length).split(sep);
	if (!parts[0]) return undefined;
	return parts[0].startsWith("@") ? parts.slice(0, 2).join("/") : parts[0];
}

function findLicense(packageRoot) {
	const candidates = readdirSync(packageRoot)
		.filter((name) => /^(license|copying|notice)(\.|$)/i.test(name))
		.sort();
	const candidate = candidates[0];
	return candidate ? readFileSync(join(packageRoot, candidate), "utf8").trim() : "";
}

function renderNotices(inputs) {
	const packageNames = new Set();
	for (const input of Object.keys(inputs)) {
		const packageName = packageNameFromInput(input);
		if (packageName) packageNames.add(packageName);
	}

	const sections = [
		"Purpose: Attribute dependencies bundled into the packaged MCP transport.",
		"Third-party notices for pi/extension/mcp-client.bundle.cjs",
		"",
		"This file is generated by pi/scripts/build.mjs.",
	];
	for (const packageName of [...packageNames].sort()) {
		const packageRoot = join(piRoot, "node_modules", ...packageName.split("/"));
		const manifest = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8"));
		const license = findLicense(packageRoot);
		sections.push(
			"",
			"=".repeat(78),
			`${manifest.name}@${manifest.version} (${manifest.license ?? "license unspecified"})`,
			"=".repeat(78),
			license || "No license file was included in the installed package.",
		);
	}
	return `${sections.join("\n")}\n`;
}

function assertCurrent(path, expected) {
	if (!existsSync(path)) {
		throw new Error(`generated file is missing: ${relative(piRoot, path)}`);
	}
	const current = readFileSync(path);
	if (!current.equals(expected)) {
		throw new Error(
			`${relative(piRoot, path)} is stale; run npm run build --prefix pi`,
		);
	}
}

const result = await build({
	bundle: true,
	entryPoints: [entryPoint],
	format: "cjs",
	legalComments: "none",
	metafile: true,
	minify: true,
	platform: "node",
	target: "node22",
	write: false,
	banner: {
		js: "// Purpose: Package the session-scoped MCP transport for native Pi tools.\n// Generated by pi/scripts/build.mjs. Do not edit by hand.",
	},
});

const bundle = result.outputFiles[0]?.contents;
if (!bundle) {
	throw new Error("esbuild did not produce a bundle");
}
const notices = Buffer.from(renderNotices(result.metafile.inputs), "utf8");

if (check) {
	assertCurrent(bundlePath, bundle);
	assertCurrent(noticesPath, notices);
	console.log("Pi MCP client bundle is current.");
} else {
	writeFileSync(bundlePath, bundle);
	writeFileSync(noticesPath, notices);
	console.log(
		`Wrote ${relative(piRoot, bundlePath)} and ${relative(piRoot, noticesPath)}.`,
	);
}
